# Generated by Django 4.2.29 on 2026-05-18 01:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lectura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=7)),
                ('lectura_actual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('m3_consumidos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('origen', models.CharField(choices=[('socio', 'Socio'), ('operario', 'Operario'), ('administrador', 'Administrador')], max_length=13)),
                ('entregado_por', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('medidor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='socios.medidor')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('medidor', 'periodo')},
            },
        ),
    ]
