# Generated by Django 4.2.29 on 2026-05-07 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_socio', models.IntegerField(unique=True)),
                ('rut', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('segundo_apellido', models.CharField(blank=True, max_length=30, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('referencia_direccion', models.CharField(max_length=500)),
                ('subsidio', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('ruta_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socios.ruta')),
            ],
        ),
        migrations.CreateModel(
            name='Medidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_medidor', models.CharField(max_length=10, unique=True)),
                ('estado_servicio', models.CharField(max_length=10)),
                ('fecha_instalacion', models.DateField(blank=True, null=True)),
                ('socio_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socios.socio')),
            ],
        ),
    ]
