# Generated by Django 4.2.29 on 2026-03-20 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='segundo_apellido',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
