# Generated by Django 4.2.29 on 2026-06-30 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medidor',
            name='estado_servicio',
            field=models.CharField(choices=[('activo', 'Activo'), ('cortado', 'Cortado'), ('retirado', 'Retirado')], default='activo', max_length=10),
        ),
    ]