# Generated by Django 4.2.29 on 2026-07-23 01:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0002_alter_medidor_estado_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='fecha_registro',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
