# Generated by Django 4.2.29 on 2026-07-26 17:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0003_alter_socio_fecha_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='fecha_registro',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
