# Generated by Django 4.2.29 on 2026-07-28 22:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0004_alter_socio_fecha_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='fecha_registro',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
