# Generated by Django 4.2.29 on 2026-06-21 23:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boletas', '0002_alter_pago_cobro'),
        ('socios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cortes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_corte', models.DateField()),
                ('lectura_corte', models.IntegerField()),
                ('fecha_reposicion', models.DateField(blank=True, null=True)),
                ('lectura_reposicion', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('cortado', 'Cortado'), ('repuesto', 'Repuesto')], default='cortado', max_length=10)),
                ('cobro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cortes', to='boletas.cobro')),
                ('operador_corte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cortes_realizados', to=settings.AUTH_USER_MODEL)),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cortes', to='socios.socio')),
            ],
            options={
                'ordering': ['-fecha_corte'],
            },
        ),
    ]
