# Generated by Django 4.2.29 on 2026-07-28 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cortes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cortes',
            name='costo_reposicion_facturado',
            field=models.BooleanField(default=False),
        ),
    ]
