# Generated by Django 4.2.29 on 2026-06-20 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lecturas', '0001_initial'),
        ('socios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=7)),
                ('cargo_fijo', models.IntegerField()),
                ('costo_m3_consumido', models.IntegerField()),
                ('corte_reposicion', models.IntegerField(blank=True, null=True)),
                ('interes_mora', models.IntegerField(blank=True, null=True)),
                ('total', models.IntegerField()),
                ('numero_boleta', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateField()),
                ('lectura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cobros', to='lecturas.lectura')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cobros', to='socios.socio')),
            ],
            options={
                'ordering': ['-periodo'],
            },
        ),
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo_fijo', models.IntegerField()),
                ('precio_m3', models.IntegerField()),
                ('vigente_desde', models.DateField()),
                ('vigente_hasta', models.DateField(null=True)),
                ('costo_corte_reposicion', models.IntegerField()),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_pagado', models.IntegerField()),
                ('forma_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia')], max_length=15)),
                ('fecha_pago', models.DateField(auto_now_add=True)),
                ('cobro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='boletas.cobro')),
            ],
        ),
        migrations.AddField(
            model_name='cobro',
            name='tarifa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cobros', to='boletas.tarifa'),
        ),
        migrations.AddConstraint(
            model_name='cobro',
            constraint=models.UniqueConstraint(fields=('socio', 'periodo'), name='unique_cobro_socio_periodo'),
        ),
    ]
