# Generated by Django 4.2.29 on 2026-06-21 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boletas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='cobro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='boletas.cobro'),
        ),
    ]
